import type { StateCreator } from 'zustand';
import type { GameState } from './gameStoreTypes';
import { defaultState } from './gameStoreTypes';

/** Slice 1: core state defaults + ships, crane, camera, training-adjacent actions */
export type Slice1 = typeof defaultState & Pick<
    GameState,
    | 'addShip'
    | 'removeShip'
    | 'setCurrentShip'
    | 'setCraneContract'
    | 'completeCraneContract'
    | 'installUpgrade'
    | 'uninstallUpgrade'
    | 'setMusicPlaying'
    | 'stopAllMusic'
    | 'setBPM'
    | 'setLyricsSize'
    | 'setLightIntensity'
    | 'setSpectatorTarget'
    | 'endSpectatorMode'
    | 'setTimeOfDay'
    | 'setCameraMode'
    | 'resetGame'
    | 'loadSavedState'
    | 'scheduleDeparture'
    | 'returnToDock'
    | 'upgradeShipVersion'
    | 'setSeason'
    | 'setWildlifeDensity'
    | 'setEnableMarineLife'
    | 'setWeather'
    | 'setQualityPreset'
    | 'setSpreaderPos'
    | 'setSpreaderRotation'
    | 'setCableDepth'
    | 'setLoadTension'
    | 'setTrolleyPosition'
    | 'setWinchSpeed'
    | 'setHighlightedUpgradePart'
    | 'setPendingAutoInstall'
    | 'setInstallQueue'
    | 'advanceInstallQueue'
    | 'abortInstallQueue'
    | 'pauseInstallQueue'
    | 'resumeInstallQueue'
    | 'setJoystickLeft'
    | 'setJoystickRight'
    | 'setTwistlockEngaged'
    | 'setHeaterActive'
    | 'setIsMoving'
    | 'setMultiviewMode'
    | 'setUnderwaterIntensity'
    | 'setDashboardPreset'
    | 'pushViewportHistory'
    | 'navigateViewportHistory'
    | 'pinViewportCamera'
    | 'recallPinnedViewportCamera'
    | 'setFocusedViewport'
    | 'addWildlife'
>;

/** Slice 2: weather hooks, economy, missions, tugboat, harbor events */
export type Slice2 = Pick<
    GameState,
    | 'removeWildlife'
    | 'updateWildlife'
    | 'setActiveSeaEvent'
    | 'addHarborEvent'
    | 'removeHarborEvent'
    | 'setEventEnabled'
    | 'setCurrentHarbor'
    | 'setCabinViewMode'
    | 'setGameTime'
    | 'setAttachmentSystemConfig'
    | 'clearLastInstallation'
    | 'setGameMode'
    | 'startTrainingModule'
    | 'exitTrainingModule'
    | 'updateTrainingProgress'
    | 'addReputation'
    | 'setOperationMode'
    | 'beginWalkingFromCab'
    | 'returnToCraneFromWalking'
    | 'updateWalkingState'
    | 'updateTugboatState'
    | 'setTugboatObjectives'
    | 'markTugboatFirstTimeViewed'
    | 'refreshSalvageContracts'
    | 'acceptSalvageContract'
    | 'submitAcousticNote'
    | 'resetAcousticHandshake'
    | 'completeTugboatObjective'
    | 'purchaseTugboatUpgrade'
    | 'resetTugboatMode'
    | 'attachTowLine'
    | 'detachTowLine'
    | 'signalTowLineSnap'
    | 'setStormIntensity'
    | 'setStormTimeRemaining'
    | 'setStormActive'
    | 'setWindDirection'
    | 'setWindStrength'
    | 'setRainDensity'
    | 'addMoney'
    | 'deductMoney'
    | 'setActiveMission'
    | 'updateMission'
    | 'completeMission'
    | 'failMission'
    | 'triggerTugboatWin'
    | 'setTugSpectatorActive'
    | 'setWaveParams'
>;

/** Convenience alias for slice factory functions */
export type GameStoreSlice<T> = StateCreator<GameState, [], [], T>;
